name: "Update Angular Action"
on:
  schedule:
    - cron: '0 0 * * 6'

jobs:
  ngxUptodate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: /frontend/
    steps:
      - name: Updating ng dependencies
        uses: tinesoft/ngx-uptodate@v1.1.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-branch-prefix: chore/ng-update/
          pr-title: 'chore (by ng-update): Update Angular dependencies'